# Generated by Django 5.2.10 on 2026-01-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='component',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='组件路径'),
        ),
    ]
