# Generated by Django 5.2.10 on 2026-01-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_menu_component'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='menu_type',
            field=models.CharField(choices=[('M', '目录'), ('C', '菜单'), ('F', '按钮')], default='C', max_length=1, verbose_name='菜单类型'),
        ),
    ]
