# Generated by Django 6.0.1 on 2026-01-26 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_menu_menu_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DictData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='字典标签')),
                ('value', models.CharField(max_length=100, verbose_name='字典键值')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认')),
                ('dict_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datas', to='system.dicttype')),
            ],
            options={
                'ordering': ['sort'],
            },
        ),
    ]
