# Generated by Django 6.0.1 on 2026-01-28 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_dictdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='menus',
            field=models.ManyToManyField(blank=True, to='system.menu', verbose_name='关联菜单'),
        ),
    ]
