# Generated by Django 6.0.1 on 2026-01-29 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_role_menus'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictdata',
            name='list_class',
            field=models.CharField(default='default', max_length=100, verbose_name='回显样式'),
        ),
    ]
