# Generated by Django 5.2.10 on 2026-01-24 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='作业标题')),
                ('content', models.TextField(verbose_name='作业要求')),
                ('deadline', models.DateTimeField(verbose_name='截止时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '作业发布',
                'verbose_name_plural': '作业发布',
                'db_table': 'tb_assignment',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='课程名称')),
                ('category', models.CharField(max_length=50, verbose_name='课程分类')),
                ('cover_img', models.ImageField(blank=True, null=True, upload_to='courses/', verbose_name='课程封面')),
                ('description', models.TextField(verbose_name='课程简介')),
                ('view_count', models.IntegerField(default=0, verbose_name='浏览量')),
                ('is_published', models.BooleanField(default=True, verbose_name='是否发布')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
                'db_table': 'tb_course',
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='assignments/', verbose_name='作业附件')),
                ('content', models.TextField(blank=True, null=True, verbose_name='文本内容')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='得分')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='教师评语')),
                ('is_graded', models.BooleanField(default=False, verbose_name='是否已批改')),
                ('submit_time', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.assignment', verbose_name='对应作业')),
            ],
            options={
                'verbose_name': '作业提交',
                'verbose_name_plural': '作业提交',
                'db_table': 'tb_assignment_submission',
            },
        ),
    ]
