# Generated by Django 5.2.10 on 2026-01-25 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'verbose_name': '作业发布', 'verbose_name_plural': '作业发布管理'},
        ),
        migrations.AlterModelOptions(
            name='assignmentsubmission',
            options={'verbose_name': '作业提交', 'verbose_name_plural': '学生作业批改'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': '课程', 'verbose_name_plural': '课程列表'},
        ),
        migrations.RemoveField(
            model_name='assignmentsubmission',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='course',
            name='is_published',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='提交学生'),
        ),
        migrations.AlterField(
            model_name='course',
            name='cover_img',
            field=models.ImageField(blank=True, null=True, upload_to='courses/', verbose_name='封面图'),
        ),
    ]
