# Generated by Django 6.0.1 on 2026-01-28 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_assignment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='outline',
            field=models.TextField(blank=True, null=True, verbose_name='课程大纲'),
        ),
        migrations.CreateModel(
            name='CourseResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='资源名称')),
                ('file', models.FileField(upload_to='course_resources/', verbose_name='文件')),
                ('resource_type', models.IntegerField(choices=[(1, '视频'), (2, '课件(PPT/PDF)'), (3, '其他资料')], default=2, verbose_name='资源类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='courses.course', verbose_name='所属课程')),
            ],
            options={
                'verbose_name': '课程资源',
                'verbose_name_plural': '课程资源',
                'db_table': 'tb_course_resource',
            },
        ),
    ]
