# Generated by Django 5.2.10 on 2026-01-25 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='aichathistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='提问时间'),
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('type', models.SmallIntegerField(choices=[(1, '普通公告'), (2, '竞赛通知'), (3, '考试提醒')], default=1, verbose_name='类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='发布人')),
            ],
            options={
                'verbose_name': '系统公告',
                'verbose_name_plural': '公告管理',
                'db_table': 'tb_notice',
            },
        ),
    ]
