# Generated by Django 6.0.1 on 2026-01-29 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_banner_privatemessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['-is_top', '-created_at'], 'verbose_name': '系统公告', 'verbose_name_plural': '公告管理'},
        ),
        migrations.AddField(
            model_name='notice',
            name='is_top',
            field=models.BooleanField(default=False, verbose_name='是否置顶'),
        ),
    ]
