# Generated by Django 6.0.1 on 2026-01-30 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_alter_notice_options_notice_is_top'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='type',
            field=models.CharField(default='1', max_length=10, verbose_name='类型'),
        ),
    ]
