# Generated by Django 5.2.10 on 2026-01-24 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='竞赛名称')),
                ('description', models.TextField(verbose_name='竞赛说明')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '编程竞赛',
                'verbose_name_plural': '编程竞赛',
                'db_table': 'tb_competition',
            },
        ),
        migrations.CreateModel(
            name='JudgeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(verbose_name='提交代码')),
                ('language', models.CharField(default='Python', max_length=20, verbose_name='编程语言')),
                ('result', models.CharField(choices=[('Pending', '排队中'), ('AC', '通过 (Accepted)'), ('WA', '答案错误 (Wrong Answer)'), ('TLE', '超时 (Time Limit Exceeded)'), ('RE', '运行错误 (Runtime Error)')], default='Pending', max_length=20, verbose_name='判题结果')),
                ('score', models.IntegerField(default=0, verbose_name='得分')),
                ('time_used', models.IntegerField(default=0, verbose_name='耗时(ms)')),
                ('memory_used', models.IntegerField(default=0, verbose_name='内存(KB)')),
                ('ai_advice', models.TextField(blank=True, null=True, verbose_name='AI代码分析建议')),
                ('submit_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '评测记录',
                'verbose_name_plural': '评测记录',
                'db_table': 'tb_judge_record',
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='题目名称')),
                ('difficulty', models.CharField(choices=[('Easy', '简单'), ('Medium', '中等'), ('Hard', '困难')], default='Easy', max_length=10, verbose_name='难度')),
                ('content', models.TextField(verbose_name='题目描述(Markdown)')),
                ('input_desc', models.TextField(null=True, verbose_name='输入描述')),
                ('output_desc', models.TextField(null=True, verbose_name='输出描述')),
                ('test_cases', models.JSONField(verbose_name='测试用例')),
                ('time_limit', models.IntegerField(default=1000, verbose_name='时间限制(ms)')),
                ('memory_limit', models.IntegerField(default=256, verbose_name='内存限制(MB)')),
            ],
            options={
                'verbose_name': '编程题目',
                'verbose_name_plural': '编程题目',
                'db_table': 'tb_problem',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, '待审核'), (1, '已通过'), (2, '已拒绝')], default=0, verbose_name='报名状态')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.competition', verbose_name='竞赛')),
            ],
            options={
                'verbose_name': '竞赛报名',
                'verbose_name_plural': '竞赛报名',
                'db_table': 'tb_enrollment',
            },
        ),
    ]
