# Generated by Django 5.2.10 on 2026-01-24 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='报名学生'),
        ),
        migrations.AddField(
            model_name='judgerecord',
            name='competition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='competitions.competition', verbose_name='所属竞赛'),
        ),
        migrations.AddField(
            model_name='judgerecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='提交者'),
        ),
        migrations.AddField(
            model_name='judgerecord',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.problem', verbose_name='题目'),
        ),
        migrations.AddField(
            model_name='competition',
            name='problems',
            field=models.ManyToManyField(related_name='competitions', to='competitions.problem', verbose_name='包含题目'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('competition', 'student')},
        ),
    ]
