# Generated by Django 5.2.10 on 2026-01-25 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competition',
            options={'verbose_name': '竞赛', 'verbose_name_plural': '竞赛活动管理'},
        ),
        migrations.AlterModelOptions(
            name='judgerecord',
            options={'verbose_name': '评测记录', 'verbose_name_plural': '评测记录/错题本'},
        ),
        migrations.AlterModelOptions(
            name='problem',
            options={'verbose_name': '题目', 'verbose_name_plural': '编程题库管理'},
        ),
        migrations.RemoveField(
            model_name='competition',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='judgerecord',
            name='ai_advice',
        ),
        migrations.RemoveField(
            model_name='judgerecord',
            name='language',
        ),
        migrations.RemoveField(
            model_name='judgerecord',
            name='memory_used',
        ),
        migrations.RemoveField(
            model_name='judgerecord',
            name='time_used',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='input_desc',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='output_desc',
        ),
        migrations.AlterField(
            model_name='competition',
            name='description',
            field=models.TextField(verbose_name='竞赛规则'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='problems',
            field=models.ManyToManyField(to='competitions.problem', verbose_name='包含题目'),
        ),
        migrations.AlterField(
            model_name='judgerecord',
            name='code',
            field=models.TextField(verbose_name='代码'),
        ),
        migrations.AlterField(
            model_name='judgerecord',
            name='result',
            field=models.CharField(choices=[('Pending', '判题中'), ('AC', '通过'), ('WA', '答案错误'), ('TLE', '超时'), ('RE', '运行错误')], default='Pending', max_length=20, verbose_name='结果'),
        ),
        migrations.AlterField(
            model_name='judgerecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='学生'),
        ),
        migrations.AlterField(
            model_name='judgerecord',
            name='submit_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='提交时间'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='test_cases',
            field=models.JSONField(verbose_name='测试用例(JSON)'),
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
