# Generated by Django 6.0.1 on 2026-01-26 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0004_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='竞赛类型'),
        ),
    ]
