# Generated by Django 6.0.1 on 2026-01-26 09:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0005_competition_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='competition',
            name='problems',
            field=models.ManyToManyField(blank=True, related_name='competitions', to='competitions.problem', verbose_name='包含题目'),
        ),
    ]
