# Generated by Django 6.0.1 on 2026-01-27 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0006_competition_created_at_alter_competition_problems'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'verbose_name': '竞赛报名', 'verbose_name_plural': '报名审核管理'},
        ),
    ]
