# Generated by Django 6.0.1 on 2026-01-27 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0007_alter_enrollment_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='WrongQuestionBook',
            fields=[
            ],
            options={
                'verbose_name': '错题',
                'verbose_name_plural': '错题本管理',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('competitions.judgerecord',),
        ),
        migrations.AlterModelOptions(
            name='judgerecord',
            options={'verbose_name': '评测记录', 'verbose_name_plural': '评测记录/成绩管理'},
        ),
    ]
