# Generated by Django 6.0.1 on 2026-01-28 03:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0008_wrongquestionbook_alter_judgerecord_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='题干')),
                ('options', models.JSONField(verbose_name='选项(JSON)')),
                ('correct_option', models.CharField(max_length=10, verbose_name='正确选项')),
                ('difficulty', models.CharField(choices=[('Easy', '简单'), ('Medium', '中等'), ('Hard', '困难')], default='Easy', max_length=10, verbose_name='难度')),
                ('score', models.IntegerField(default=5, verbose_name='默认分值')),
            ],
            options={
                'verbose_name': '选择题',
                'verbose_name_plural': '选择题库',
                'db_table': 'tb_choice_problem',
            },
        ),
        migrations.CreateModel(
            name='ExamPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='试卷标题')),
                ('description', models.TextField(blank=True, null=True, verbose_name='试卷说明')),
                ('duration', models.IntegerField(default=90, verbose_name='考试时长(分钟)')),
                ('total_score', models.IntegerField(default=100, verbose_name='总分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('choice_problems', models.ManyToManyField(blank=True, to='competitions.choiceproblem', verbose_name='包含选择题')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='出卷人')),
                ('programming_problems', models.ManyToManyField(blank=True, to='competitions.problem', verbose_name='包含编程题')),
            ],
            options={
                'verbose_name': '试卷',
                'verbose_name_plural': '试卷管理',
                'db_table': 'tb_exam_paper',
            },
        ),
    ]
