# Generated by Django 6.0.1 on 2026-01-30 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0009_choiceproblem_exampaper'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='cover_img',
            field=models.ImageField(blank=True, null=True, upload_to='competitions/', verbose_name='封面图'),
        ),
    ]
