# Generated by Django 5.2.10 on 2026-01-25 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户管理'},
        ),
        migrations.AlterField(
            model_name='user',
            name='class_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='班级'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.SmallIntegerField(choices=[(1, '学生'), (2, '教师'), (3, '管理员')], default=1, verbose_name='角色'),
        ),
    ]
