# Generated by Django 6.0.1 on 2026-01-26 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_classinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='class_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='users.classinfo', verbose_name='所属班级'),
        ),
    ]
