# Generated by Django 6.0.1 on 2026-01-28 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_role_menus'),
        ('users', '0004_user_class_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='system_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.role', verbose_name='系统角色'),
        ),
    ]
